<p>By counting carefully it can be seen that a rectangular grid measuring $3$ by $2$ contains eighteen rectangles:</p>
<div class="center">
<img src="img.png" class="dark_img" alt=""></div>
<p>Although there exists no rectangular grid that contains exactly two million rectangles, find the area of the grid with the nearest solution.</p>

<p>A brute force look at number of rectangles found for the first (row, col) $\in 1, 2, 3, 4, 5$ has the following table-</p>

```
 | 1 | 2 | 3 | 4 | 5 |
 |---|---|---|---|---|
1| 1 | 3 | 6 |10 |15 |
2| 3 | 9 |18 |30 |45 |
3| 6 |18 |36 |60 |90 |
4|10 |30 |60 |100|150|
5|15 |45 |90 |150|225|
```

<p>This table is symmetric, such that for any kind of future analysis it may be helpful to know that $A^T = A$. Notice that the sequence $f(n) = 1, 3, 6, 10, 15, ...$ for $n = 1, 2, 3, 4, 5, ...$ found in the first row or column is the sequence for triangular numbers, as seen below explicitly-</p>

$$T_n = \sum_{k = 1}^n k = \frac{n(n + 1)}{2}$$

<p>Notice now that for each successive row after the first, the same sequence of triangular numbers can be found, just with an additional factor. This additional factor is a triangular number based on the column of the table.</p>

$$\text{row 1} \rightarrow \frac{k(k + 1)}{2}, k \in \mathbb{N}$$
$$\text{row 2} \rightarrow 3\frac{k(k + 1)}{2}, k \in \mathbb{N}$$
$$\text{row 3} \rightarrow 6\frac{k(k + 1)}{2}, k \in \mathbb{N}$$
$$\cdots$$
$$\text{row n} \rightarrow \left(\frac{n(n + 1)}{2}\right)\left(\frac{k(k + 1)}{2}\right), n,k \in \mathbb{N}$$

<p>Altogether, let $n$ be a row index and let $k$ be a col index for a table $s$, where $n, k \in \mathbb{N}$. Then, the table entry at $[n, k]$ is-</p>
$$s[n, k] = \left(\frac{n(n + 1)}{2}\right)\left(\frac{k(k + 1)}{2}\right)$$

<p>We want an $n, k$ such that $s[n, k] \approx 2,000,000$. This can be found using a brute force minimum update routine.</p>

In [2]:
TARGET: int = 2000000

# Triangular number (2D) function
T = lambda n, k: int(0.5 * n * (n + 1) * 0.5 * k * (k + 1))

# Main loop
if __name__ == "__main__":
    min_diff: int = TARGET
    for i in range(1, 100):
        for j in range(1, 100):
            temp_val: int = abs(TARGET - T(i, j))
            if temp_val < min_diff:
                    min_diff = temp_val
                    print("{0}, ({1}, {2})".format(min_diff, i, j))

1999999, (1, 1)
1999997, (1, 2)
1999994, (1, 3)
1999990, (1, 4)
1999985, (1, 5)
1999979, (1, 6)
1999972, (1, 7)
1999964, (1, 8)
1999955, (1, 9)
1999945, (1, 10)
1999934, (1, 11)
1999922, (1, 12)
1999909, (1, 13)
1999895, (1, 14)
1999880, (1, 15)
1999864, (1, 16)
1999847, (1, 17)
1999829, (1, 18)
1999810, (1, 19)
1999790, (1, 20)
1999769, (1, 21)
1999747, (1, 22)
1999724, (1, 23)
1999700, (1, 24)
1999675, (1, 25)
1999649, (1, 26)
1999622, (1, 27)
1999594, (1, 28)
1999565, (1, 29)
1999535, (1, 30)
1999504, (1, 31)
1999472, (1, 32)
1999439, (1, 33)
1999405, (1, 34)
1999370, (1, 35)
1999334, (1, 36)
1999297, (1, 37)
1999259, (1, 38)
1999220, (1, 39)
1999180, (1, 40)
1999139, (1, 41)
1999097, (1, 42)
1999054, (1, 43)
1999010, (1, 44)
1998965, (1, 45)
1998919, (1, 46)
1998872, (1, 47)
1998824, (1, 48)
1998775, (1, 49)
1998725, (1, 50)
1998674, (1, 51)
1998622, (1, 52)
1998569, (1, 53)
1998515, (1, 54)
1998460, (1, 55)
1998404, (1, 56)
1998347, (1, 57)
1998289, (1, 58)
1998230, (1, 59)
1998170, (1, 60)
1998109, (1, 61)
1998047, (1, 62)
1997984, (1, 63)
1997920, (1, 64)
1997855, (1, 65)
1997789, (1, 66)
1997722, (1, 67)
1997654, (1, 68)
1997585, (1, 69)
1997515, (1, 70)
1997444, (1, 71)
1997372, (1, 72)
1997299, (1, 73)
1997225, (1, 74)
1997150, (1, 75)
1997074, (1, 76)
1996997, (1, 77)
1996919, (1, 78)
1996840, (1, 79)
1996760, (1, 80)
1996679, (1, 81)
1996597, (1, 82)
1996514, (1, 83)
1996430, (1, 84)
1996345, (1, 85)
1996259, (1, 86)
1996172, (1, 87)
1996084, (1, 88)
1995995, (1, 89)
1995905, (1, 90)
1995814, (1, 91)
1995722, (1, 92)
1995629, (1, 93)
1995535, (1, 94)
1995440, (1, 95)
1995344, (1, 96)
1995247, (1, 97)
1995149, (1, 98)
1995050, (1, 99)
1995041, (2, 57)
1994867, (2, 58)
1994690, (2, 59)
1994510, (2, 60)
1994327, (2, 61)
1994141, (2, 62)
1993952, (2, 63)
1993760, (2, 64)
1993565, (2, 65)
1993367, (2, 66)
1993166, (2, 67)
1992962, (2, 68)
1992755, (2, 69)
1992545, (2, 70)
1992332, (2, 71)
1992116, (2, 72)
1991897, (2, 73)
1991675, (2, 74)
1991450, (2, 75)
1991222, (2, 76)
1990991, (2, 77)
1990757, (2, 78)
1990520, (2, 79)
1990280, (2, 80)
1990037, (2, 81)
1989791, (2, 82)
1989542, (2, 83)
1989290, (2, 84)
1989035, (2, 85)
1988777, (2, 86)
1988516, (2, 87)
1988252, (2, 88)
1987985, (2, 89)
1987715, (2, 90)
1987442, (2, 91)
1987166, (2, 92)
1986887, (2, 93)
1986605, (2, 94)
1986320, (2, 95)
1986032, (2, 96)
1985741, (2, 97)
1985447, (2, 98)
1985150, (2, 99)
1985090, (3, 70)
1984664, (3, 71)
1984232, (3, 72)
1983794, (3, 73)
1983350, (3, 74)
1982900, (3, 75)
1982444, (3, 76)
1981982, (3, 77)
1981514, (3, 78)
1981040, (3, 79)
1980560, (3, 80)
1980074, (3, 81)
1979582, (3, 82)
1979084, (3, 83)
1978580, (3, 84)
1978070, (3, 85)
1977554, (3, 86)
1977032, (3, 87)
1976504, (3, 88)
1975970, (3, 89)
1975430, (3, 90)
1974884, (3, 91)
1974332, (3, 92)
1973774, (3, 93)
1973210, (3, 94)
1972640, (3, 95)
1972064, (3, 96)
1971482, (3, 97)
1970894, (3, 98)
1970300, (3, 99)
1969970, (4, 77)
1969190, (4, 78)
1968400, (4, 79)
1967600, (4, 80)
1966790, (4, 81)
1965970, (4, 82)
1965140, (4, 83)
1964300, (4, 84)
1963450, (4, 85)
1962590, (4, 86)
1961720, (4, 87)
1960840, (4, 88)
1959950, (4, 89)
1959050, (4, 90)
1958140, (4, 91)
1957220, (4, 92)
1956290, (4, 93)
1955350, (4, 94)
1954400, (4, 95)
1953440, (4, 96)
1952470, (4, 97)
1951490, (4, 98)
1950500, (4, 99)
1950185, (5, 81)
1948955, (5, 82)
1947710, (5, 83)
1946450, (5, 84)
1945175, (5, 85)
1943885, (5, 86)
1942580, (5, 87)
1941260, (5, 88)
1939925, (5, 89)
1938575, (5, 90)
1937210, (5, 91)
1935830, (5, 92)
1934435, (5, 93)
1933025, (5, 94)
1931600, (5, 95)
1930160, (5, 96)
1928705, (5, 97)
1927235, (5, 98)
1925750, (5, 99)
1925030, (6, 84)
1923245, (6, 85)
1921439, (6, 86)
1919612, (6, 87)
1917764, (6, 88)
1915895, (6, 89)
1914005, (6, 90)
1912094, (6, 91)
1910162, (6, 92)
1908209, (6, 93)
1906235, (6, 94)
1904240, (6, 95)
1902224, (6, 96)
1900187, (6, 97)
1898129, (6, 98)
1896050, (6, 99)
1895252, (7, 86)
1892816, (7, 87)
1890352, (7, 88)
1887860, (7, 89)
1885340, (7, 90)
1882792, (7, 91)
1880216, (7, 92)
1877612, (7, 93)
1874980, (7, 94)
1872320, (7, 95)
1869632, (7, 96)
1866916, (7, 97)
1864172, (7, 98)
1861400, (7, 99)
1859024, (8, 88)
1855820, (8, 89)
1852580, (8, 90)
1849304, (8, 91)
1845992, (8, 92)
1842644, (8, 93)
1839260, (8, 94)
1835840, (8, 95)
1832384, (8, 96)
1828892, (8, 97)
1825364, (8, 98)
1821800, (8, 99)
1819775, (9, 89)
1815725, (9, 90)
1811630, (9, 91)
1807490, (9, 92)
1803305, (9, 93)
1799075, (9, 94)
1794800, (9, 95)
1790480, (9, 96)
1786115, (9, 97)
1781705, (9, 98)
1777250, (9, 99)
1774775, (10, 90)
1769770, (10, 91)
1764710, (10, 92)
1759595, (10, 93)
1754425, (10, 94)
1749200, (10, 95)
1743920, (10, 96)
1738585, (10, 97)
1733195, (10, 98)
1727750, (10, 99)
1723724, (11, 91)
1717652, (11, 92)
1711514, (11, 93)
1705310, (11, 94)
1699040, (11, 95)
1692704, (11, 96)
1686302, (11, 97)
1679834, (11, 98)
1673300, (11, 99)
1666316, (12, 92)
1659062, (12, 93)
1651730, (12, 94)
1644320, (12, 95)
1636832, (12, 96)
1629266, (12, 97)
1621622, (12, 98)
1613900, (12, 99)
1610702, (13, 92)
1602239, (13, 93)
1593685, (13, 94)
1585040, (13, 95)
1576304, (13, 96)
1567477, (13, 97)
1558559, (13, 98)
1549550, (13, 99)
1541045, (14, 93)
1531175, (14, 94)
1521200, (14, 95)
1511120, (14, 96)
1500935, (14, 97)
1490645, (14, 98)
1480250, (14, 99)
1475480, (15, 93)
1464200, (15, 94)
1452800, (15, 95)
1441280, (15, 96)
1429640, (15, 97)
1417880, (15, 98)
1406000, (15, 99)
1405544, (16, 93)
1392760, (16, 94)
1379840, (16, 95)
1366784, (16, 96)
1353592, (16, 97)
1340264, (16, 98)
1326800, (16, 99)
1316855, (17, 94)
1302320, (17, 95)
1287632, (17, 96)
1272791, (17, 97)
1257797, (17, 98)
1242650, (17, 99)
1236485, (18, 94)
1220240, (18, 95)
1203824, (18, 96)
1187237, (18, 97)
1170479, (18, 98)
1153550, (18, 99)
1151650, (19, 94)
1133600, (19, 95)
1115360, (19, 96)
1096930, (19, 97)
1078310, (19, 98)
1059500, (19, 99)
1042400, (20, 95)
1022240, (20, 96)
1001870, (20, 97)
981290, (20, 98)
960500, (20, 99)
946640, (21, 95)
924464, (21, 96)
902057, (21, 97)
879419, (21, 98)
856550, (21, 99)
846320, (22, 95)
822032, (22, 96)
797491, (22, 97)
772697, (22, 98)
747650, (22, 99)
741440, (23, 95)
714944, (23, 96)
688172, (23, 97)
661124, (23, 98)
633800, (23, 99)
632000, (24, 95)
603200, (24, 96)
574100, (24, 97)
544700, (24, 98)
515000, (24, 99)
486800, (25, 96)
455275, (25, 97)
423425, (25, 98)
391250, (25, 99)
365744, (26, 96)
331697, (26, 97)
297299, (26, 98)
262550, (26, 99)
240032, (27, 96)
203366, (27, 97)
166322, (27, 98)
128900, (27, 99)
109664, (28, 96)
70282, (28, 97)
30494, (28, 98)
9700, (28, 99)
2770, (33, 84)
2, (36, 77)

<p>A 36x77 rectangle contains 1999998 recatngles, which is the closest in value to our target.</p>